### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jenkin** [sparkfabrik/nominatim-openapi#1]
Here I'm proposing final goals and a development roadmap for this project, discussion is open!

- [x] OpenAPI specification following the official documentation: https://nominatim.org/release-docs/develop/ (please read also [Nominatim/discussions/3115](https://github.com/osm-search/Nominatim/discussions/3115#discussioncomment-6486249) and [geocodejson-spec/issues/21](https://github.com/geocoders/geocodejson-spec/issues/21#issue-447726501) and #2)
- [ ] Some examples using code generators (ie. [swagger codegen](https://swagger.io/tools/swagger-codegen/) or [api](https://api.readme.dev/docs)) and mapping libraries (ie. [leaflet](https://leafletjs.com/))
- [ ] A nodejs CLI (and npm package) using modern (ie. esm) and best practices
- [ ] A containerized version of playground
